import Config

# Host configuration
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :uneebee, UneebeeWeb.Endpoint,
  force_ssl: [hsts: true],
  http: [port: {:system, "PORT"}],
  url: [host: System.get_env("UNEEBEE_HOST")],
  cache_static_manifest: "priv/static/cache_manifest.json",
  https: [
    port: 443,
    cipher_suite: :strong,
    otp_app: :uneebee,
    keyfile: System.get_env("UNEEBEE_SSL_KEY_PATH"),
    certfile: System.get_env("UNEEBEE_SSL_CERT_PATH"),
    # OPTIONAL Key for intermediate certificates:
    cacertfile: System.get_env("INTERMEDIATE_CERTFILE_PATH")
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Uneebee.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
